#pragma once
void ANIM_PostInit();
/*ANIM_AddManipulator(ANIM_Mixer *,ANIM_Manipulator *)
ANIM_AddSecondary(ANIM_Mixer *,ANIM_Secondary *)
ANIM_AdvanceTime(ANIM_Instance *,float,void (*)(AnimTuning_Event *,void *),void *)
ANIM_AllocJointMatrices(uint)
ANIM_Animate(AnimState *,ANIM_Instance *,uint *,bool)
ANIM_AnimateMixer(AnimState *,ANIM_Mixer *)
ANIM_ApplyManipulator(AnimState *,ANIM_Manipulator *,bool)
ANIM_ApplyManipulators(AnimState *,ANIM_Mixer *,bool)
ANIM_Begin(AnimState *)
ANIM_BlendTo(ANIM_Mixer *,ANIM_Instance *,GDE_Animation const*,AnimLoopMode,AnimBlendMode,float,float,bool,bool,void (*)(AnimTuning_Event *,void *),void *)
ANIM_ChildSnapshot(AnimState *,GDE_SkeletonInfo *,uchar *,GDE_BoneComponents *,uint,uint)
ANIM_ClearEndFlag(ANIM_Instance *)
ANIM_ComponentsToMatrix(GDE_BoneComponents *,MATRIX44 *,float)
ANIM_CreateInstance(GDE_AnimationHeader const*,GDE_SkeletonInfo **,uint,ANIM_Instance *)
ANIM_CreateOutputMatrices(AnimState *)
ANIM_DebugClear(AnimState *)
ANIM_DebugInverseBindPose(AnimState *,GDE_SkeletonInfo *)
ANIM_DestroyInstance(ANIM_Instance *)
ANIM_DrawSkeleton(AnimState *,GDE_SkeletonInfo **,float,uint)
ANIM_End(AnimState *)
ANIM_EventSeek(ANIM_Instance *,void (*)(AnimTuning_Event *,void *),void *)
ANIM_GetBoneComponents(AnimState *,GDE_Animation const*,GDE_AnimBoneController *,float,ANIM_BoneKeyframeCursor *,GDE_BoneComponents *,int,bool)
ANIM_GetBoneComponents(AnimState *,int)
ANIM_GetBoneKeyframeRot(VEC4 &,uchar **)
ANIM_GetBoneKeyframeRot64Bit(VEC4 &,uchar **)
ANIM_GetBoneKeyframeRot_Uncompressed(VEC4 &,uchar **)
ANIM_GetBoneMatrix(AnimState const*,uint,bool)
ANIM_GetBoneMatrix(MATRIX44 *,GDE_BoneComponents const*)
ANIM_GetBonePosition(AnimState *,uint,bool)
ANIM_GetBoneToLocalMatrix(AnimState *,ANIM_Mixer const*,MATRIX44 *,int)
ANIM_GetMorphComponents(AnimState *,GDE_Animation const*,GDE_AnimMorphController *,float,ANIM_MorphKeyframeCursor *,GDE_MorphComponents *,bool)
ANIM_GetParentBoneIndex(GDE_SkeletonInfo const*,uint,bool)
ANIM_GetParentBoneMatrix(AnimState *,uint,bool)
ANIM_GetSkinnedPos(AnimState *,VEC3 *,VEC3 const*,ANIM_JointWeightPair const*,int,GDE_SkeletonInfo *)
ANIM_GetTokenString(GDE_Animation *,char *)
ANIM_HitEnd(ANIM_Instance const*)
ANIM_InitManipulator(ANIM_Manipulator *,uchar,uchar)
ANIM_InitMixer(ANIM_Mixer *)
ANIM_InitSecondary(ANIM_Secondary *,ANIM_Instance *,GDE_SkeletonInfo **,uint,uint)
ANIM_IsBlending(ANIM_Instance *)
ANIM_IsBlending(ANIM_Mixer const*)
ANIM_IsBlendingOut(ANIM_Instance *)
ANIM_IsLooping(ANIM_Instance *)
ANIM_IsSecondaryActive(ANIM_Secondary *,bool)
ANIM_ManualDefineEvent(GDE_Animation *,AnimTuning_EventType,AnimTuning_Event *)
ANIM_ManualDefineEvent(GDE_Animation *,AnimTuning_EventType,AnimTuning_Event const&)
ANIM_MixerClearEndFlag(ANIM_Mixer *)
ANIM_MixerHitEnd(ANIM_Mixer const*)
ANIM_MixerIsLooping(ANIM_Mixer const*)
ANIM_MultiplyComponents(GDE_BoneComponents *,GDE_BoneComponents *,GDE_BoneComponents *,uchar)
ANIM_OneBoneInit(ANIM_OneBoneLookAt *,short,short,float)
ANIM_PlayStartAndEndEvents(GDE_Animation const*,GDE_Animation const*,void (*)(AnimTuning_Event *,void *),void *)
ANIM_RemoveManipulator(ANIM_Mixer *,ANIM_Manipulator *)
ANIM_RemoveSecondary(ANIM_Mixer *,ANIM_Secondary *)
ANIM_ReserveJointMatrixMemory(int)
ANIM_ResetCursorCache(ANIM_Instance *)
ANIM_SecondarySnapTo(ANIM_Secondary *,float,float,float)
ANIM_SeekBone(GDE_Animation const*,GDE_AnimBoneController *,ANIM_BoneKeyframeCursor *,float,uchar **,uchar **,float *,bool)
ANIM_SeekMorph(GDE_Animation const*,GDE_AnimMorphController *,ANIM_MorphKeyframeCursor *,float,uchar **,uchar **,float *,bool)
ANIM_SetAllComponentsDefault(AnimState *,GDE_SkeletonInfo *)
ANIM_SetAutoBlend(ANIM_BlendInfo *,bool,float,float)
ANIM_SetDefaultComponents(AnimState *,int,int,int,float,bool)
ANIM_SetInstanceAnimation(GDE_Animation const*,ANIM_Instance *)
ANIM_SetSecondaryAnimation(ANIM_Secondary *,GDE_Animation *,uchar *)
ANIM_SnapTo(ANIM_Mixer *,GDE_Animation const*,ANIM_Instance *,AnimLoopMode,float,void (*)(AnimTuning_Event *,void *),void *)
ANIM_SnapTo_Internal(ANIM_Mixer *,ANIM_Instance *,AnimLoopMode,float,void (*)(AnimTuning_Event *,void *),void *)
ANIM_Snapshot(ANIM_Mixer *,uint,GDE_SkeletonInfo *)
ANIM_SwapJointMatrixBuffers(int)
ANIM_TryAllocCursors(ANIM_Instance *)
ANIM_Update(ANIM_Mixer *,float,void (*)(AnimTuning_Event *,void *),void *)
ANIM_UpdateBlendInfo(ANIM_BlendInfo *,float,float *)
ANIM_UsePausedContext(bool)*/