#pragma once
struct BikeEntity;
struct PrivateAttributesHelper;
struct BikeManager { //0x9E98 bytes
    inline static std::unique_ptr<BikeManager> g_pBikeManager;
    std::vector<BikeEntity *> m_field_9D08, m_field_9CD8, m_field_9CF0;
    BikeManager(/*EventSystem *, bool*/);
    //static void Shutdown() { g_pBikeManager.reset(); }
    static BikeManager *Instance() { 
        /*TODO*/
        if (!IsInitialized()) 
            g_pBikeManager.reset(new BikeManager()); 
        zassert(g_pBikeManager.get() != nullptr); 
        return g_pBikeManager.get(); 
    }
    static bool IsInitialized() { return g_pBikeManager.get() != nullptr; }
    void Initialize(Experimentation *exp);
    ~BikeManager();
    BikeEntity *m_mainBike;
    PrivateAttributesHelper *m_pah;
    BikeEntity *FindBikeWithNetworkID(int64_t id, bool);
    void ProcessPlayerState(zwiftUpdateContext *zuc, const protobuf::PlayerState &pst);
/*BikeManager::AddAvatarAnimationJob(EntityAnimationData *)
BikeManager::AddNetworkBike(long long)
BikeManager::AddPartner(BikeEntity *)
BikeManager::AdjustSpeedForPacking(std::vector<BikeEntity *> &,bool,float)
BikeManager::AwakeSleepingNetworkBike(long long)
BikeManager::BikeManager(void)
BikeManager::BikeSideOn(BikeEntity *,BikeEntity *)
BikeManager::CalculatePlayerProximity(void)
BikeManager::CalculateRidingOffsets(float &,float &,float,int,float,float,float,float,bool)
BikeManager::CameraSortAndCullBikes(float,VEC3 const&,int,BikeEntity *)
BikeManager::CheckHandCycleFeatureFlag(Experiment::Variant)
BikeManager::Destroy(Experiment::IExperimentation<Experiment::Feature> &)
BikeManager::DistPointToLine(VEC3,VEC3,VEC3)
BikeManager::DoAllBikeAnimationsJob(JobData *)
BikeManager::DraftTest(VEC3,BikeEntity *,std::vector<BikeEntity *>,BikeEntity **)
BikeManager::DrawABike(uint,uint,uint,float,float,float,float,uint)
BikeManager::DrawPlayerBikeForCustomization(float,float,float)
BikeManager::DrawWheelset(uint,uint,float,float,float)
BikeManager::DropInOnBike(long long)
BikeManager::FindActiveIndex(void)
BikeManager::FindAnyBikeInEvent(long long)
BikeManager::GetAIBike(int)
BikeManager::GetClubsForCurrentPlayer(std::function<void ()(std::vector<zwift::protobuf::club::ClubWithMembership> const&,int)> const&)
BikeManager::GetNetworkBike(int)
BikeManager::GetRoadBounds(RoadSegment *,float,float *,float *,float *,float *,bool)
BikeManager::GroupAIsHere(int,double,bool)
BikeManager::InitCameraAngleSwitchAroundPlayer(std::vector<VEC3> const&,VEC3 const&,float)
BikeManager::InitializePackDynamicsConfig(Experiment::Variant)
BikeManager::IsFeatureFlagEnabled(Experiment::Feature)
BikeManager::IsPackDynamicsV4AutoBrakeVisualsEnabled(void)
BikeManager::IsPackDynamicsV4Enabled(void)
BikeManager::IsPlayerOfType(zwift::protobuf::PlayerType,BikeEntity const&)
BikeManager::IsPositionAccuracyOverNetworkEnabled(void)
BikeManager::IsZwiftStaff(BikeEntity const&)
BikeManager::LineSideOn(VEC3,VEC3,VEC3)
BikeManager::LoadAssets(void)
BikeManager::OnAnimationsAllFinished(int,JobData *)
BikeManager::PlayerBike_ClearBikeSession(void)
BikeManager::PlayerBike_ClearJerseySession(void)
BikeManager::PlayerBike_GetBike(void)
BikeManager::PlayerBike_GetBodyType(BikeManager::BodyType &)
BikeManager::PlayerBike_GetEarings(void)
BikeManager::PlayerBike_GetFacialHair(void)
BikeManager::PlayerBike_GetFacialHairColor(void)
BikeManager::PlayerBike_GetFrameHue(void)
BikeManager::PlayerBike_GetFramePaintjob(void)
BikeManager::PlayerBike_GetFrontWheel(void)
BikeManager::PlayerBike_GetGlasses(void)
BikeManager::PlayerBike_GetGloves(void)
BikeManager::PlayerBike_GetHair(void)
BikeManager::PlayerBike_GetHairColor(void)
BikeManager::PlayerBike_GetHeadType(void)
BikeManager::PlayerBike_GetHelmet(void)
BikeManager::PlayerBike_GetJersey(void)
BikeManager::PlayerBike_GetRearWheel(void)
BikeManager::PlayerBike_GetRunShortsLength(void)
BikeManager::PlayerBike_GetRunningArmAccessory(void)
BikeManager::PlayerBike_GetRunningHeadGear(void)
BikeManager::PlayerBike_GetRunningShirt(void)
BikeManager::PlayerBike_GetRunningShoes(void)
BikeManager::PlayerBike_GetRunningShorts(void)
BikeManager::PlayerBike_GetRunningSocks(void)
BikeManager::PlayerBike_GetShoes(void)
BikeManager::PlayerBike_GetSocks(void)
BikeManager::PlayerBike_GetSocksLength(void)
BikeManager::PlayerBike_GetTattoos(void)
BikeManager::PlayerBike_GetWatches(void)
BikeManager::PlayerBike_SetBike(uint)
BikeManager::PlayerBike_SetBikeSession(uint)
BikeManager::PlayerBike_SetBodyType(BikeManager::BodyType)
BikeManager::PlayerBike_SetCyclingSocks(uint)
BikeManager::PlayerBike_SetEarings(uint)
BikeManager::PlayerBike_SetFacialHair(uint)
BikeManager::PlayerBike_SetFacialHairColor(uint)
BikeManager::PlayerBike_SetFrameHue(uchar)
BikeManager::PlayerBike_SetFramePaintjob(uint)
BikeManager::PlayerBike_SetFrontWheel(uint)
BikeManager::PlayerBike_SetGlasses(uint)
BikeManager::PlayerBike_SetGloves(uint)
BikeManager::PlayerBike_SetHair(uint)
BikeManager::PlayerBike_SetHairColor(uint)
BikeManager::PlayerBike_SetHeadType(uint)
BikeManager::PlayerBike_SetHelmet(uint)
BikeManager::PlayerBike_SetJersey(uint)
BikeManager::PlayerBike_SetJerseySession(uint)
BikeManager::PlayerBike_SetRearWheel(uint)
BikeManager::PlayerBike_SetRunShortsLength(uint)
BikeManager::PlayerBike_SetRunningArmAccessory(uint)
BikeManager::PlayerBike_SetRunningHeadGear(uint)
BikeManager::PlayerBike_SetRunningShirt(uint)
BikeManager::PlayerBike_SetRunningShoes(uint)
BikeManager::PlayerBike_SetRunningShorts(uint)
BikeManager::PlayerBike_SetRunningSocks(uint)
BikeManager::PlayerBike_SetShoes(uint)
BikeManager::PlayerBike_SetSocks(uint)
BikeManager::PlayerBike_SetSocksLength(uint)
BikeManager::PlayerBike_SetTattoos(uint)
BikeManager::PlayerBike_SetWatches(uint)
BikeManager::ProcessClubs(zwift::protobuf::club::Clubs const&,std::function<void ()(std::vector<zwift::protobuf::club::ClubWithMembership> const&,int)> const&)
BikeManager::PutAllBikesToSleep(void)
BikeManager::RemovePartner(BikeEntity *)
BikeManager::ResetBikesForNewLevel(void)
BikeManager::ResetRideOnTintOverride(void)
BikeManager::SetActiveClub(std::string const&)
BikeManager::SetRideOnTintOverride(VEC4 const&)
BikeManager::SetRideOnTintOverride(zwift::entity::bike::RideOnTint)
BikeManager::SleepNetworkBikes(zwiftUpdateContext &)
BikeManager::SwarmAIsAroundGivenBikes(std::vector<BikeEntity *> const&,std::vector<BikeEntity *> const&)
BikeManager::UpdateAI(zwiftUpdateContext &,float)
BikeManager::UpdateFeatureFlags(void)
BikeManager::WaitForAllThreadedAnimationsToBeDone(void)
BikeManager::~BikeManager()*/
};
