#pragma once
enum BLE_SOURCE { BLES_ZCA = 1 };
struct BLEModule : public EventObject {
    inline static std::unique_ptr<BLEModule> g_BLEModule;
    BLEModule(Experimentation *exp);
    static void Initialize(Experimentation *exp);
    static bool IsInitialized() { return g_BLEModule.get() != nullptr; }
    static BLEModule *Instance() { zassert(g_BLEModule.get() != nullptr); return g_BLEModule.get(); }
    static void Shutdown();
    void HandleEvent(EVENT_ID, va_list) override;
    void StopScan();
    void ProcessDiscovery(const protobuf::BLEAdvertisement &, BLE_SOURCE);
    void ProcessBLEResponse(const protobuf::BLEPeripheralResponse &, BLE_SOURCE);

    /*BLEModule::BLEModule(Experiment::IExperimentation<Experiment::Feature> &)
BLEModule::DidConnect(char const*,char const*)
BLEModule::DidReceiveError(char const*,char const*,BLE_ERROR_TYPE,uint)
BLEModule::DidRecover(char const*,char const*)
BLEModule::DoHardwarePrompt(void)
BLEModule::EnableDeviceDiscovery(bool)
BLEModule::GetRSSI(char const*)
BLEModule::HasBLE(void)
BLEModule::IBLEBackend::~IBLEBackend()
BLEModule::IgnoreReceivedBluetoothPackets(bool)
BLEModule::Initialize(Experiment::IExperimentation<Experiment::Feature> &)
BLEModule::InitializeBLE(void)
BLEModule::Instance(void)
BLEModule::IsAnyDeviceConnecting(void)
BLEModule::IsAutoConnectPairingOn(void)
BLEModule::IsBLEAvailable(void)
BLEModule::IsInitialized(void)
BLEModule::IsRecoveringLostDevices(void)
BLEModule::IsScanning(void)
BLEModule::LegacyBLEImpl::DidConnect(char const*,char const*)
BLEModule::LegacyBLEImpl::DidReceiveError(char const*,char const*,BLE_ERROR_TYPE,uint)
BLEModule::LegacyBLEImpl::DidRecover(char const*,char const*)
BLEModule::LegacyBLEImpl::DoHardwarePrompt(void)
BLEModule::LegacyBLEImpl::EnableDeviceDiscovery(bool)
BLEModule::LegacyBLEImpl::GetRSSI(char const*)
BLEModule::LegacyBLEImpl::HasBLE(void)
BLEModule::LegacyBLEImpl::IgnoreReceivedBluetoothPackets(bool)
BLEModule::LegacyBLEImpl::InitializeBLE(void)
BLEModule::LegacyBLEImpl::IsAnyDeviceConnecting(void)
BLEModule::LegacyBLEImpl::IsAutoConnectPairingOn(void)
BLEModule::LegacyBLEImpl::IsBLEAvailable(void)
BLEModule::LegacyBLEImpl::IsRecoveringLostDevices(void)
BLEModule::LegacyBLEImpl::IsScanning(void)
BLEModule::LegacyBLEImpl::PairDevice(BLEDevice const&)
BLEModule::LegacyBLEImpl::PairDevice(std::string const&)
BLEModule::LegacyBLEImpl::ProcessAdvertisedServiceUUIDs(zwift::protobuf::BLEAdvertisement const&,std::string const&,zwift::protobuf::BLEAdvertisementDataSection_Type,BLE_SOURCE)
BLEModule::LegacyBLEImpl::ProcessAdvertisementManufacturerData(zwift::protobuf::BLEAdvertisement const&,std::string const&,BLE_SOURCE)
BLEModule::LegacyBLEImpl::ProcessBLEResponse(zwift::protobuf::BLEPeripheralResponse const&,BLE_SOURCE)
BLEModule::LegacyBLEImpl::ProcessDiscovery(zwift::protobuf::BLEAdvertisement const&,BLE_SOURCE)
BLEModule::LegacyBLEImpl::PurgeDeviceList(void)
BLEModule::LegacyBLEImpl::ReceivedRSSI(int,char const*,char const*)
BLEModule::LegacyBLEImpl::SendValueToDevice(zwift::protobuf::BLEPeripheralRequest const&,BLE_SOURCE)
BLEModule::LegacyBLEImpl::SetAutoConnectPairingMode(bool)
BLEModule::LegacyBLEImpl::SetDeviceConnectedFlag(zwift::protobuf::BLEPeripheralResponse const&,bool)
BLEModule::LegacyBLEImpl::StartBackgroundBLECommunication(void)
BLEModule::LegacyBLEImpl::StartScan(zwift::protobuf::BLEPeripheralRequest const&)
BLEModule::LegacyBLEImpl::StartSearchForLostDevices(void)
BLEModule::LegacyBLEImpl::StopBackgroundBLECommunication(void)
BLEModule::LegacyBLEImpl::StopScan(void)
BLEModule::LegacyBLEImpl::StopSearchForLostDevices(void)
BLEModule::LegacyBLEImpl::UnpairDevice(BLEDevice const&)
BLEModule::LegacyBLEImpl::~LegacyBLEImpl()
BLEModule::PairDevice(BLEDevice const&)
BLEModule::PairDevice(std::string const&)
BLEModule::ProcessAdvertisedServiceUUIDs(zwift::protobuf::BLEAdvertisement const&,std::string const&,zwift::protobuf::BLEAdvertisementDataSection_Type,BLE_SOURCE)
BLEModule::ProcessAdvertisementManufacturerData(zwift::protobuf::BLEAdvertisement const&,std::string const&,BLE_SOURCE)
BLEModule::PurgeDeviceList(void)
BLEModule::ReceivedRSSI(int,char const*,char const*)
BLEModule::SendValueToDevice(zwift::protobuf::BLEPeripheralRequest const&,BLE_SOURCE)
BLEModule::SetAutoConnectPairingMode(bool)
BLEModule::SetDeviceConnectedFlag(zwift::protobuf::BLEPeripheralResponse const&,bool)
BLEModule::Shutdown(void)
BLEModule::StartBackgroundBLECommunication(void)
BLEModule::StartScan(zwift::protobuf::BLEPeripheralRequest const&)
BLEModule::StartSearchForLostDevices(void)
BLEModule::StopBackgroundBLECommunication(void)
BLEModule::StopScan(void)
BLEModule::StopSearchForLostDevices(void)
BLEModule::ToggleBLEPacketLogging(void)
BLEModule::UnpairDevice(BLEDevice const&)
BLEModule::Update(void)
BLEModule::callBoolImplMethodOrLogIfUninitialized(std::function<bool ()(void)>,std::string)
BLEModule::callVoidImplMethodOrLogIfUninitialized(std::function<void ()(void)>,std::string)
BLEModule::~BLEModule()*/
};
