#pragma once
enum FONT_STYLE { FS_SMALL, FS_SANSERIF, FS_FONDO_MED, FS_FONDO_BLACK, FS_CNT };
enum LANGUAGE_IDS { LID_03 = 3, LID_CNT = 4 };
struct CFont2D_struc24 {
    std::vector<float> m_cont;
};
struct CFont2D_glyph {
    char field_0;
    char field_1;
    char m_kernIdx;
    char field_3;
    char field_4;
    char field_5;
    char field_6;
    char field_7;
    char field_8;
    char field_9;
    char field_A;
    char field_B;
    float m_width;
    char field_10;
    char field_11;
    char field_12;
    char field_13;
};
struct CFont2D_info {
    int m_someCnt;
    char field_0[200];
    float m_kern[LID_CNT];
    char field_DC[1008];
    char field_4C8[1220];
    uint16_t m_glyphIndexes[65536];
};
struct CFont2D_cache { //192 bytes
    char gap[192];
};
class CFont2D {
public:
    std::string m_string;
    CFont2D_struc24 m_struc24x4[4];
    float m_kern[LID_CNT];
    CFont2D_info m_info;
    CFont2D_glyph *m_glyphs;
    void *m_allocPtr;
    float m_field_20A30;
    char m_field_20A34;
    char field_20A35;
    char field_20A36;
    char field_20A37;
    char field_20A38;
    char field_20A39;
    char field_20A3A;
    char field_20A3B;
    float m_field_20A3C;
    float m_scale;
    float m_kerning;
    float m_baseLine;
    float m_headLine;
    char m_field_20A50;
    char field_20A51;
    char field_20A52;
    char field_20A53;
    float m_field_20A54;
    char m_field_20A58;
    char m_field_20A59;
    char field_20A5A;
    char field_20A5B;
    char field_20A5C;
    char field_20A5D;
    char field_20A5E;
    char field_20A5F;
    CFont2D_cache *m_cache;
    uint32_t m_cacheCnt, m_cacheCntUsed;
    int m_curCache;
    char field_20A74;
    char field_20A75;
    char field_20A76;
    char field_20A77;
    std::deque<VEC2> m_hbStack;

    CFont2D();
    void Load(FONT_STYLE s);
    void SetScaleAndKerning(float scale, float kerning);
    void LoadDirectEast(const char *name1, const char *name2);
    bool LoadDirect(const char *name);
    bool PopHeadBase();
    void PushHeadBase(float head, float base);
    float GetBaseline(float mult);
    float GetHeadline(float mult);
    float StringWidthW(const char *text);
    float StringWidthW(const UChar *uText);
    float StringWidthW(const UChar *uText, uint32_t len);
    float GetBoundedScaleW(float w, float h, const UChar *uText);
    float GetHeight();
    CFont2D_cache *CacheMallocCharacters(uint32_t, bool);
    void StartCaching(uint32_t);
    int EndCachingAndRender(bool uiProjection);
    void RenderAllCachedContent(bool uiProjection);
    bool LoadFont(const char *name);
    bool LoadFontFromWad(const char *name);
    bool LoadFontWFromWadV3(const char *name);
    bool LoadFontWV3(const char *name);
    ~CFont2D();

    void GetParagraphBoxSize(const char *text, float, float, float);

    void BreakString(float, const char *, float);
    void CharWidthW(uint16_t);
    void CreateFontHelper(void *);
    void CreateFontHelperFilename(const char *);
    void Ellipsize(float, const char *, float);
    void Ellipsize(float, const UChar *, float);
    void FitCharsToWidth(const char *, int);
    void FitCharsToWidthW(const UChar *, int);
    void FitParagraphInBox(float, float, const UChar *);
    void FitWordsToWidth(const char *, int, float);
    void FitWordsToWidthW(const char *, int, float);
    void FitWordsToWidthW(const UChar *, int, float);
    void GetBaseOffset(float, float);
    void GetBoundedScale(float, float, const char *);
    void GetCenteredOffset(float, float);
    //void GetGlyphUVView(uint32_t, tViewport<float> &, uint32_t *);
    //void GetGlyphView(uint32_t, tViewport<int> &);
    void GetHeadOffset(float, float);
    void GetHeadToBase(float);
    void GetHeadToBottom(float);
    void GetParagraphIndexByPosition(float, float, float, float, const UChar *, int, float, float, float *, float *);
    void GetParagraphLineCount(float, const char *, float, float, bool);
    void GetParagraphLineCountW(float, const char *, float, float, bool);
    void GetParagraphLineCountW(float, const UChar *, float, float, bool);
    void GetParagraphPositionByIndex(int, float, float, const char *, int, float, float);
    void GetParagraphPositionByIndex(int, float, float, const UChar *, int, float, float);
    void GetScaleAndKerning(float *, float *);
    void GetTexture(uint32_t);
    void GetTopToBase(float);
    void ImbueCommas(uint32_t);
    void IsFontTextureLoaded(uint16_t);
    void LoadLanguageTextures(int);
    void RenderBorderedString(float, float, const char *, uint32_t, int, float, bool, bool, float, uint32_t);
    void RenderBorderedStringMultisized(float, float, int, const char **, uint32_t *, float *, int, int, bool, int, bool);
    void RenderBorderedWString(float, float, const char *, uint32_t, int, float, bool, bool, uint32_t);
    void RenderBorderedWString(float, float, const UChar *, uint32_t, int, float, bool, bool, uint32_t);
    void RenderBorderedWStringMultisized(float, float, int, const char **, uint32_t *, float *, int, int, bool, int, bool);
    void RenderBorderedWStringMultisized(float, float, int, const UChar **, uint32_t *, float *, int, int, bool, int, bool);
    void RenderParagraph(float, float, float, float, const char *, uint32_t, int, float, bool, float, float);
    void RenderParagraphW(float, float, float, float, const char *, uint32_t, int, float, bool, float, float);
    void RenderParagraphW(float, float, float, float, const UChar *, uint32_t, int, float, bool, float, float);
    void RenderString(float, float, const char *, uint32_t, int, float, bool, bool, float, bool);
    void RenderStringBounded(float, float, float, float, const char *, uint32_t, int, bool, bool);
    void RenderStringMultisized(float, float, int, const char **, uint32_t *, float *, int, int, bool, int, bool);
    void RenderStringRT(float, float, const char *, uint32_t, int, float, bool, bool);
    void RenderWString(float, float, const char *, uint32_t, int, float, bool, bool);
    void RenderWString(float, float, const UChar *, uint32_t, int, float, bool, bool, bool);
    void RenderWStringBounded(float, float, float, float, const UChar *, uint32_t, int, bool, bool);
    void RenderWStringMultisized(float, float, int, const char **, uint32_t *, float *, int, int, bool, int, bool);
    void RenderWStringMultisized(float, float, int, const UChar **, uint32_t *, float *, int, int, bool, int, bool);
    void RenderWStringRT(float, float, const char *, uint32_t, int, float, bool, bool);
    void RenderWStringRT(float, float, const UChar *, uint32_t, int, float, bool, bool);
    void SetHeadAndBaseLines(float, float);
    void SetLanguageKerningScalar(LANGUAGE_IDS, float);
    void SetSpaceScale(float);
    void SetVerticalOffset(float);
};
struct BufSafeToUTF8 { UChar m_buf[512]; int m_usageCounter = 0; };
UChar *SafeToUTF8(const char *ansi, BufSafeToUTF8  *buf);

inline CFont2D *g_ChatFontGW, *g_ChatFontLW, g_GiantFontW, g_LargeFontW, g_debugFont, g_SmallFont, g_MediumFont;
inline const bool g_bSupportFontCaching = true;