#pragma once
struct BikeEntity;
struct EbikeBoost {
    int m_stateBits = 0;
    void ActivateBoost(BikeEntity *);
    void ActivateBoost(bool);
    void ActivateCharge(BikeEntity *);
    void ActivateCharge(bool);
};
/*
EbikeBoost::Deserialize(ulong long,std::string const&)
EbikeBoost::DrawBatteryStatus(float,float,float,float)
EbikeBoost::EbikeBoost(BikeEntity *)
EbikeBoost::FindEventStartTime(BikeEntity *)
EbikeBoost::GetActiveBoostOption(void)
EbikeBoost::GetBatteryLevel(void)
EbikeBoost::GetBatteryWeightKg(void)
EbikeBoost::GetPowerWatts(void)
EbikeBoost::GetSelectedBoostOption(void)
EbikeBoost::IsBoostEquipped(BikeEntity *)
EbikeBoost::IsEbikeEvent(ulong long)
EbikeBoost::IsEventStarted(void)
EbikeBoost::IsPowerupDiscardable(void)
EbikeBoost::Recharge(float)
EbikeBoost::SetBoostEffect(EbikeBoostOption)
EbikeBoost::SetCurrentBoostOption(EbikeBoostOption,float)
EbikeBoost::ShowBoostOptionMenu(bool)
EbikeBoost::Update(float)
EbikeBoost::~EbikeBoost()
EbikeBoostGUI::AutoMoveWithActionBar(void)
EbikeBoostGUI::Deserialize(ulong long,std::string const&)
EbikeBoostGUI::DrawBattery(float,float,float,float,float)
EbikeBoostGUI::DrawBatteryFrame(EbikeBoostInfo const&,float,float,float,float,float,uint)
EbikeBoostGUI::DrawBatteryLevel(EbikeBoostInfo const&,float,float,float,float)
EbikeBoostGUI::DrawHUDExtension(float,float,float,float,bool)
EbikeBoostGUI::EbikeBoostGUI(EbikeBoost *)
EbikeBoostGUI::PreloadTextures(void)
EbikeBoostGUI::Render(void)
EbikeBoostGUI::RenderEditMode(void)
EbikeBoostGUI::RenderRideMode(void)
EbikeBoostGUI::SetControlMode(EbikeBoostGUI::ControlMode)
EbikeBoostGUI::Update(float)
EbikeBoostGUI::~EbikeBoostGUI()
EbikeBoostHelpMenu::EbikeBoostHelpMenu(void)
EbikeBoostHelpMenu::OnEscape(void)
EbikeBoostHelpMenu::OnMouseUp(float,float)
EbikeBoostHelpMenu::OnNextButtonClicked(void *)
EbikeBoostHelpMenu::Render(void)
EbikeBoostHelpMenu::RenderPage0(void)
EbikeBoostHelpMenu::RenderPage1(void)
EbikeBoostHelpMenu::Update(float)
EbikeBoostHelpMenu::~EbikeBoostHelpMenu()
EbikeBoostInfo::GetEbikeBoostInfo(EbikeBoostOption)
EbikeBoostSelectionMenu::DrawSelectionStats(float,float,float,float)
EbikeBoostSelectionMenu::DrawSelectionWidgets(void)
EbikeBoostSelectionMenu::DrawStatsBar(char const*,float,float,float,float,float,uint,float,uint,uint)
EbikeBoostSelectionMenu::DrawStatsCount(char const*,float,float,float,float,float,int,int,uint,int,uint,uint)
EbikeBoostSelectionMenu::EbikeBoostSelectionMenu(void)
EbikeBoostSelectionMenu::GetBoostOption(GUI_Button *)
EbikeBoostSelectionMenu::GetHighlightedSelectionButton(void)
EbikeBoostSelectionMenu::GetSelectionButton(EbikeBoostOption)
EbikeBoostSelectionMenu::HighlightButton(GUI_Button *)
EbikeBoostSelectionMenu::OnEscape(void)
EbikeBoostSelectionMenu::OnHelpButtonClicked(void *)
EbikeBoostSelectionMenu::OnMouseUp(float,float)
EbikeBoostSelectionMenu::OnReadyButtonClicked(void *)
EbikeBoostSelectionMenu::OnSelectionButtonClicked(void *,void *,float,float)
EbikeBoostSelectionMenu::PostRender(void)
EbikeBoostSelectionMenu::Render(void)
EbikeBoostSelectionMenu::SelectBoostOption(EbikeBoostOption)
EbikeBoostSelectionMenu::Update(float)
EbikeBoostSelectionMenu::~EbikeBoostSelectionMenu()
EbikeBoostSelectionWidget::EbikeBoostSelectionWidget(float,float,float,float,char const*,EbikeBoostOption,GUI_Obj *)
EbikeBoostSelectionWidget::InFocus(void)
EbikeBoostSelectionWidget::OnEquipButtonClicked(void *)
EbikeBoostSelectionWidget::OnMouseDown(float,float)
EbikeBoostSelectionWidget::OnMouseUp(float,float)
EbikeBoostSelectionWidget::OutFocus(void)
EbikeBoostSelectionWidget::PostRender(void)
EbikeBoostSelectionWidget::Render(void)
EbikeBoostSelectionWidget::StretchHeight(float)
EbikeBoostSelectionWidget::Update(float)
EbikeBoostSelectionWidget::UpdateHeight(float)
EbikeBoostSelectionWidget::~EbikeBoostSelectionWidget()
EbikeBoostSurvey::EbikeBoostSurvey(void)
EbikeBoostSurvey::OnEscape(void)
EbikeBoostSurvey::OnSubmitClicked(void *,void *,float,float)
EbikeBoostSurvey::Render(void)
EbikeBoostSurvey::Update(float)
EbikeBoostSurvey::~EbikeBoostSurvey()*/